### ISSUE TITLE
(maybe) endless loop at getFavorites

### ISSUE THREAD

**Issue by TobiVanHelsinki** [thingywhat/FurAffinity-Favorites-Downloader#1]
Hi,

while trying to download my favorites, the script rans very long. I inserted a Print at line 60 to debug. the print was printed out at least 1500 Times, but i have just 70 Favorites. Skript was also running several hours. So I think, this might be a bug. 

Inserted debug print:
```
print "get fav ID $page\n";
} while($page++);
```

I used Strawberry Perl Portable Edition Version 5.28 at Windows10. At Parameter I used -u <Name> -v.

**Comment by Crinklewott** [comment]
Thanks for the report!

It seems like FurAffinity changed how their pagination works--it's no longer just by a page number. I pushed an update that should fix this. (Also oof, I wonder how long that's been broken?)

**Comment by TobiVanHelsinki** [comment]
It is working now, but really slow, hope there are not more erros.
Anyway, thank you so much for fixing and replying that quick. It helps me a lot.
(I think it was brooken for a while ^^')

**Comment by Crinklewott** [comment]
Hee, glad I could help! ^^
